version: "3"
services:
  zookeeper:
    image: bitnami/zookeeper:${ZOOKEEPER_VERSION}
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_4LW_COMMANDS_WHITELIST=ruok
    healthcheck:
      test: echo 'ruok' | nc localhost 2181 | grep imok
  kafka:
    image: bitnami/kafka:${KAFKA_VERSION}
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      zookeeper:
        condition: service_healthy
  bytehoops-producer:
    image: ghcr.io/tuxiedev/bytehoops
    ports:
      - 8080:8080
    command:
      - producer
      - -b
      - kafka:9092
      - -t
      - prometheus
    depends_on:
      - kafka
  bytehoops-consumer:
    image: ghcr.io/tuxiedev/bytehoops
    command:
      - consumer
      - -b
      - kafka:9092
      - -t
      - prometheus
      - -s
      - http://cortex:9009/api/v1/push
    depends_on:
      - kafka
  cortex:
    image: quay.io/cortexproject/cortex:${CORTEX_VERSION}
    ports:
      - 9009:9009
    volumes:
      - ./etc/cortex.yml:/etc/cortex.yml
    command:
      - -config.file=/etc/cortex.yml